apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  type: NodePort
  selector:
    app: elasticsearch
  ports:
    - port: 9200
      targetPort: 9200
      nodePort: 30092
      name: http
    - port: 9300
      targetPort: 9300
      name: transport
